# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


##############################################################################
#                                                                            #
# Author :       Falix Chong                                                 #
# Created on :   16 Aug 2017                                                 #
# Description :  HL Peers and CLI docker settings                            #
#                                                                            #
##############################################################################
#                                                                            #
# Version History :                                                          #
# 16 Aug 2017: Initial Version                                               #
#                                                                            #
##############################################################################


version: '2'

networks:
  mufg:

services:

  peer1.org3.sla.mufg.com:
    image: ibmblockchain/fabric-peer
    container_name: peer1.org3.sla.mufg.com
    environment:
      - CORE_PEER_ID=peer1.org3.sla.mufg.com
      - CORE_PEER_ADDRESS=peer1.org3.sla.mufg.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.sla.mufg.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.sla.mufg.com:7051
      - CORE_PEER_LOCALMSPID=MUFGSLApeerorg3
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_mufg
      - CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org3.sla.mufg.com/peers/peer1.org3.sla.mufg.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.sla.mufg.com/peers/peer1.org3.sla.mufg.com/tls:/etc/hyperledger/fabric/tls
        - /var/hyperledger/org3/peer1:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - mufg