# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
# This vagrantfile creates a VM with the development environment
# configured and ready to go.
#
# The setup script (env var $script) in this file installs docker.
# This is not in the setup.sh file because the docker install needs
# to be secure when running on a real linux machine.
# The docker environment that is installed by this script is not secure,
# it depends on the host being secure.
#
# At the end of the setup script in this file, a call is made
# to run setup.sh to create the developer environment.

# This is the mount point for the sync_folders of the source

# Composer - Start
module OS
  def OS.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end

  def OS.mac?
    (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def OS.unix?
    !OS.windows?
  end

  def OS.linux?
    OS.unix? and not OS.mac?
  end
end
# Composer - End

SRCMOUNT = "/hyperledger"
LOCALDEV = "/local-dev"

$script = <<SCRIPT
set -x

echo "127.0.0.1 couchdb" | tee -a /etc/hosts

export DOCKER_STORAGE_BACKEND="#{ENV['DOCKER_STORAGE_BACKEND']}"

cd #{SRCMOUNT}/devenv
./setup.sh

SCRIPT

Vagrant.require_version ">= 1.7.4"
Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/xenial64"
  
  # Composer - Start
  
  config.ssh.forward_agent = true

  # start with a Ubuntu install
  config.vm.box = "ubuntu/xenial64"

  # configure root user .profile to avoid 'stdin: is not a tty' messages
  # see https://github.com/mitchellh/vagrant/issues/1673
  config.vm.provision "configure-root-profile", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  # configure vagrant user .profile
  config.vm.provision "configure-user-profile", type: "shell", path: "bootstrap-user-profile.sh", privileged: false

  # install required software
  config.vm.provision "bootstrap-root", type: "shell", path: "bootstrap-root.sh"
  config.vm.provision "bootstrap-user", type: "shell", path: "bootstrap-user.sh", privileged: false

  # Composer - End
  
  config.vm.network :forwarded_port, guest: 7050, host: 7050, id: "orderer", host_ip: "localhost", auto_correct: true # fabric orderer service
  config.vm.network :forwarded_port, guest: 7051, host: 7051, id: "peer", host_ip: "localhost", auto_correct: true # fabric peer service
  config.vm.network :forwarded_port, guest: 7053, host: 7053, id: "peer_event", host_ip: "localhost", auto_correct: true # fabric peer event service
  config.vm.network :forwarded_port, guest: 7054, host: 7054, id: "ca", host_ip: "localhost", auto_correct: true # fabric-ca service
  config.vm.network :forwarded_port, guest: 5984, host: 15984, id: "couchdb", host_ip: "localhost", auto_correct: true # CouchDB service
  
  config.vm.network :forwarded_port, guest: 7056, host: 7056, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7058, host: 7058, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 8051, host: 8051, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 8053, host: 8053, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 8054, host: 8054, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 8056, host: 8056, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 8058, host: 8058, host_ip: "localhost", auto_correct: true
  
  # Composer - Start  
  config.vm.network :forwarded_port, guest: 7501, host: 7501, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7502, host: 7502, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7503, host: 7503, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7504, host: 7504, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7505, host: 7505, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7506, host: 7506, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7507, host: 7507, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7508, host: 7508, host_ip: "localhost", auto_correct: true
  
  config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 3000, host: 3000, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 4200, host: 4200, host_ip: "localhost", auto_correct: true
  config.vm.network :forwarded_port, guest: 7070, host: 7070, host_ip: "localhost", auto_correct: true
  # Composer - Start
  
  config.vm.synced_folder "../../fabric-sdk-java/src/test/fixture/sdkintegration", "/opt/gopath/src/github.com/hyperledger/fabric/sdkintegration"
  
  config.vm.synced_folder "..", "#{SRCMOUNT}"
  config.vm.synced_folder "..", "/opt/gopath/src/github.com/hyperledger/fabric"
  config.vm.synced_folder ENV.fetch('LOCALDEVDIR', ".."), "#{LOCALDEV}"
  
  #if File.exist?("../../fabric-ca")
  #  config.vm.synced_folder "../../fabric-ca", "/opt/gopath/src/github.com/hyperledger/fabric-ca"
  #end

  config.vm.provider :virtualbox do |vb|
    vb.name = "learnfabric"
    vb.customize ['modifyvm', :id, '--memory', '4096']
    vb.cpus = 2

    storage_backend = ENV['DOCKER_STORAGE_BACKEND']
    case storage_backend
    when nil,"","aufs","AUFS"
      # No extra work to be done
    when "btrfs","BTRFS"
      # Add a second disk for the btrfs volume
      IO.popen("VBoxManage list systemproperties") { |f|

        success = false
        while line = f.gets do
          # Find the directory where the machine images are stored
          machine_folder = line.sub(/^Default machine folder:\s*/,"")

          if line != machine_folder
            btrfs_disk = File.join(machine_folder, vb.name, 'btrfs.vdi')

            unless File.exist?(btrfs_disk)
              # Create the disk if it doesn't already exist
              vb.customize ['createhd', '--filename', btrfs_disk, '--format', 'VDI', '--size', 20 * 1024]
            end

            # Add the disk to the VM
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', btrfs_disk]
            success = true

            break
          end
        end
        raise Vagrant::Errors::VagrantError.new, "Could not provision btrfs disk" if !success
      }
    else
      raise Vagrant::Errors::VagrantError.new, "Unknown storage backend type: #{storage_backend}"
    end

  end

  config.vm.provision :shell, inline: $script
end
